(in-package :cl-info)
(let (
(deffn-defvr-pairs '(
; CONTENT: (<INDEX TOPIC> . (<FILENAME> <BYTE OFFSET> <LENGTH IN CHARACTERS> <NODE NAME>))
("df_count" . ("dataframes.info" 14857 152 "Function df_count col"))
("df_describe" . ("dataframes.info" 18477 404 "Function df_describe T"))
("df_median" . ("dataframes.info" 15390 164 "Function df_median col"))
("df_ndarray_to_table" . ("dataframes.info" 13268 287 "Function df_ndarray_to_table A names"))
("df_nunique" . ("dataframes.info" 17135 148 "Function df_nunique col"))
("df_quantile" . ("dataframes.info" 15942 173 "Function df_quantile col p"))
("df_string_column" . ("dataframes.info" 5164 186 "Function df_string_column list"))
("df_string_column_length" . ("dataframes.info" 7816 128 "Function df_string_column_length col"))
("df_string_column_p" . ("dataframes.info" 6459 154 "Function df_string_column_p x"))
("df_string_column_ref" . ("dataframes.info" 7105 177 "Function df_string_column_ref col i"))
("df_table" . ("dataframes.info" 8596 317 "Function df_table names columns"))
("df_table_column" . ("dataframes.info" 9627 251 "Function df_table_column T name"))
("df_table_head" . ("dataframes.info" 11621 238 "Function df_table_head T / df_table_head T n"))
("df_table_names" . ("dataframes.info" 11054 131 "Function df_table_names T"))
("df_table_p" . ("dataframes.info" 14078 138 "Function df_table_p x"))
("df_table_shape" . ("dataframes.info" 10510 116 "Function df_table_shape T"))
("df_table_to_ndarray" . ("dataframes.info" 12480 273 "Function df_table_to_ndarray T"))
("df_to_string_list" . ("dataframes.info" 5932 130 "Function df_to_string_list col"))
("df_unique" . ("dataframes.info" 16591 176 "Function df_unique col"))
("df_value_counts" . ("dataframes.info" 17690 240 "Function df_value_counts col"))
))
(section-pairs '(
; CONTENT: (<NODE NAME> . (<FILENAME> <BYTE OFFSET> <LENGTH IN CHARACTERS>))
("Definitions for dataframes" . ("dataframes.info" 3904 63))
("Introduction to dataframes" . ("dataframes.info" 563 523))
("String Columns" . ("dataframes.info" 4075 966))
)))
(load-info-hashtables (maxima::maxima-load-pathname-directory) deffn-defvr-pairs section-pairs))
