(in-package :cl-info)
(let (
(deffn-defvr-pairs '(
; CONTENT: (<INDEX TOPIC> . (<FILENAME> <BYTE OFFSET> <LENGTH IN CHARACTERS> <NODE NAME>))
("df_arrange" . ("dataframes.info" 22228 255 "Function df_arrange T col_name / df_arrange T col_name descending"))
("df_bind_cols" . ("dataframes.info" 29662 164 "Function df_bind_cols T1 T2"))
("df_bind_rows" . ("dataframes.info" 29131 133 "Function df_bind_rows T1 T2"))
("df_count" . ("dataframes.info" 16017 152 "Function df_count col"))
("df_describe" . ("dataframes.info" 19671 404 "Function df_describe T"))
("df_distinct" . ("dataframes.info" 25457 175 "Function df_distinct T / df_distinct T cols"))
("df_duckdb_arrange" . ("dataframes.info" 36627 226 "Function df_duckdb_arrange T column / df_duckdb_arrange T column descending"))
("df_duckdb_close" . ("dataframes.info" 40014 196 "Function df_duckdb_close"))
("df_duckdb_filter" . ("dataframes.info" 35758 233 "Function df_duckdb_filter T where_clause"))
("df_duckdb_group_summarize" . ("dataframes.info" 38489 294 "Function df_duckdb_group_summarize T group_col name1 expr1 ..."))
("df_duckdb_join" . ("dataframes.info" 37500 211 "Function df_duckdb_join T1 T2 key / df_duckdb_join T1 T2 key left"))
("df_duckdb_status" . ("dataframes.info" 39525 149 "Function df_duckdb_status"))
("df_filter" . ("dataframes.info" 20887 177 "Function df_filter T pred"))
("df_group_by" . ("dataframes.info" 26127 227 "Function df_group_by T col_name"))
("df_grouped_table_p" . ("dataframes.info" 27024 154 "Function df_grouped_table_p x"))
("df_inner_join" . ("dataframes.info" 27803 167 "Function df_inner_join T1 T2 key"))
("df_left_join" . ("dataframes.info" 28596 225 "Function df_left_join T1 T2 key"))
("df_median" . ("dataframes.info" 16550 164 "Function df_median col"))
("df_mutate" . ("dataframes.info" 23861 248 "Function df_mutate T col_name pred"))
("df_ndarray_to_table" . ("dataframes.info" 14428 287 "Function df_ndarray_to_table A names"))
("df_nunique" . ("dataframes.info" 18295 148 "Function df_nunique col"))
("df_quantile" . ("dataframes.info" 17102 173 "Function df_quantile col p"))
("df_read_csv" . ("dataframes.info" 30657 166 "Function df_read_csv path"))
("df_read_json" . ("dataframes.info" 31737 148 "Function df_read_json path"))
("df_read_parquet" . ("dataframes.info" 31266 108 "Function df_read_parquet path"))
("df_register" . ("dataframes.info" 34525 230 "Function df_register T name"))
("df_rename" . ("dataframes.info" 23398 99 "Function df_rename T old_name new_name"))
("df_select" . ("dataframes.info" 21678 108 "Function df_select T names"))
("df_slice" . ("dataframes.info" 22939 107 "Function df_slice T indices"))
("df_sql" . ("dataframes.info" 33241 243 "Function df_sql query"))
("df_sql_run" . ("dataframes.info" 34034 148 "Function df_sql_run query"))
("df_string_column" . ("dataframes.info" 6324 186 "Function df_string_column list"))
("df_string_column_length" . ("dataframes.info" 8976 128 "Function df_string_column_length col"))
("df_string_column_p" . ("dataframes.info" 7619 154 "Function df_string_column_p x"))
("df_string_column_ref" . ("dataframes.info" 8265 177 "Function df_string_column_ref col i"))
("df_summarize" . ("dataframes.info" 24612 373 "Function df_summarize T name1 fn1 name2 fn2 ..."))
("df_table" . ("dataframes.info" 9756 317 "Function df_table names columns"))
("df_table_column" . ("dataframes.info" 10787 251 "Function df_table_column T name"))
("df_table_head" . ("dataframes.info" 12781 238 "Function df_table_head T / df_table_head T n"))
("df_table_names" . ("dataframes.info" 12214 131 "Function df_table_names T"))
("df_table_p" . ("dataframes.info" 15238 138 "Function df_table_p x"))
("df_table_shape" . ("dataframes.info" 11670 116 "Function df_table_shape T"))
("df_table_to_ndarray" . ("dataframes.info" 13640 273 "Function df_table_to_ndarray T"))
("df_to_string_list" . ("dataframes.info" 7092 130 "Function df_to_string_list col"))
("df_unique" . ("dataframes.info" 17751 176 "Function df_unique col"))
("df_unregister" . ("dataframes.info" 35296 114 "Function df_unregister name"))
("df_value_counts" . ("dataframes.info" 18850 240 "Function df_value_counts col"))
("df_write_csv" . ("dataframes.info" 32242 119 "Function df_write_csv T path"))
("df_write_parquet" . ("dataframes.info" 32803 111 "Function df_write_parquet T path"))
))
(section-pairs '(
; CONTENT: (<NODE NAME> . (<FILENAME> <BYTE OFFSET> <LENGTH IN CHARACTERS>))
("Definitions for dataframes" . ("dataframes.info" 3904 63))
("Introduction to dataframes" . ("dataframes.info" 563 523))
("String Columns" . ("dataframes.info" 4075 2126))
)))
(load-info-hashtables (maxima::maxima-load-pathname-directory) deffn-defvr-pairs section-pairs))
