(in-package :cl-info)
(let (
(deffn-defvr-pairs '(
; CONTENT: (<INDEX TOPIC> . (<FILENAME> <BYTE OFFSET> <LENGTH IN CHARACTERS> <NODE NAME>))
("df_ndarray_to_table" . ("dataframes.info" 13069 287 "Function df_ndarray_to_table A names"))
("df_string_column" . ("dataframes.info" 4965 186 "Function df_string_column list"))
("df_string_column_length" . ("dataframes.info" 7617 128 "Function df_string_column_length col"))
("df_string_column_p" . ("dataframes.info" 6260 154 "Function df_string_column_p x"))
("df_string_column_ref" . ("dataframes.info" 6906 177 "Function df_string_column_ref col i"))
("df_table" . ("dataframes.info" 8397 317 "Function df_table names columns"))
("df_table_column" . ("dataframes.info" 9428 251 "Function df_table_column T name"))
("df_table_head" . ("dataframes.info" 11422 238 "Function df_table_head T / df_table_head T n"))
("df_table_names" . ("dataframes.info" 10855 131 "Function df_table_names T"))
("df_table_p" . ("dataframes.info" 13849 138 "Function df_table_p x"))
("df_table_shape" . ("dataframes.info" 10311 116 "Function df_table_shape T"))
("df_table_to_ndarray" . ("dataframes.info" 12281 273 "Function df_table_to_ndarray T"))
("df_to_string_list" . ("dataframes.info" 5733 130 "Function df_to_string_list col"))
))
(section-pairs '(
; CONTENT: (<NODE NAME> . (<FILENAME> <BYTE OFFSET> <LENGTH IN CHARACTERS>))
("Definitions for dataframes" . ("dataframes.info" 3904 63))
("Introduction to dataframes" . ("dataframes.info" 563 523))
("String Columns" . ("dataframes.info" 4075 767))
)))
(load-info-hashtables (maxima::maxima-load-pathname-directory) deffn-defvr-pairs section-pairs))
